# file task dowmload_filebeat_rpm.yml
#
#

---
- name: "Download Filebeat's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
    dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
  register: download_filebeat
  until: download_filebeat is succeeded
