---
# file for task "Install Filebeat"
#
#

- name: Install Filebeat
   become: true
   yum:
    name: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
    state: present
   notify: restart filebeat
