---
# Files for tasks "Set filebeat systemwork"
#
#
#

- name: Set filebeat systemwork
  become: true
  command:
    cmd: filebeat modules enable system
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is alredy enabled'
